#!/bin/sh
# /etc/init.d/vncserver

### BEGIN INIT INFO
# Provides: vncserver
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start VNC Server at boot time
# Description: Start VNC Server at boot time.
### END INIT INFO

USER=pi
HOME=/home/pi
DISPLAY=0
GEOMETRY=1366x768

# export USER HOME

case "$1" in
start)
	echo "Starting VNC Server"
	su --login $USER <<- END-SU
		/usr/bin/vncserver :$DISPLAY -geometry $GEOMETRY -depth 24
	END-SU
	;; 

stop)
	echo "Stopping VNC Server"
	/usr/bin/vncserver -kill $DISPLAY
	;;

*)
	echo "Usage: /etc/init.d/vncserver {start|stop}"
	exit 1
	;;
esac

exit 0
